# Copyright 2021 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: mlx
  namespace: kubeflow
spec:
  owner:
    kind: User
    name: mlx@ibm.com
